spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: developer
    url: jdbc:mysql://120.79.24.63:3306/ss_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: developer
ss: 
  fileroot: D:/develop/nginx-1.12.1/