server:
  port: 8010
spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: developer
    url: jdbc:mysql://120.79.24.63:3306/ss_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: developer
  application:
    name: starrysea-activity
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true
ss: 
  fileroot: D:/develop/nginx-1.12.1/