spring: 
  application: 
      name: starrysea-order
  mail:
    host: smtp.starrysea.top
    password: Xingzhihai2017
    port: '25'
    properties:
      mail:
        smtp:
          auth: 'true'
    username: mumuzhizhi@starrysea.top
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true